version: 2.1

jobs:
  echo-workflow-id:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run:
          name: Workflow ID
          command: |
            echo "CIRCLE_WORKFLOW_ID = ${CIRCLE_WORKFLOW_ID}"
            echo "SHORT CIRCLE_WORKFLOW_ID = ${CIRCLE_WORKFLOW_ID:0:7}"

  build:
    docker:
      - image: vistaprintufi/docker-aws-build
      # - image: hireme/docker-aws-cli:1.0.1
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Test commands
          command: |
            echo $PWD
            ls
            docker --version
            aws --version
      - run:
          name: "Django: Build, tag and push image"
          command: |
            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $ECR_URI

            export REPOSITORY_URI="520099902592.dkr.ecr.us-east-1.amazonaws.com/cstreet_api_production_django"

            export IMAGE_TAG="${CIRCLE_WORKFLOW_ID:0:7}"

            sh deployment/build/django.sh
      - run:
          name: "Update task"
          command: |
            export REPOSITORY_URI="520099902592.dkr.ecr.us-east-1.amazonaws.com/cstreet_api_production_django"

            export IMAGE_TAG="${CIRCLE_WORKFLOW_ID:0:7}"

            mkdir deployment/tasks

            aws ecs describe-task-definition \
              --task-definition backend \
              --query taskDefinition > deployment/tasks/backend-task-def.json

            python3 deployment/scripts/update_task_definition.py \
              --container-name django \
              --image-uri "${REPOSITORY_URI}:${IMAGE_TAG}" \
              --task-definition deployment/tasks/backend-task-def.json

            cat deployment/tasks/backend-task-def.json


workflows:
  default:
    jobs:
      - echo-workflow-id
      - build
