version: 2.1

jobs:
  echo-workflow-id:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run:
          name: Workflow ID
          command: |
            echo "CIRCLE_WORKFLOW_ID = ${CIRCLE_WORKFLOW_ID}"
            echo "SHORT CIRCLE_WORKFLOW_ID = ${CIRCLE_WORKFLOW_ID:0:7}"

  static-checks:
    docker:
      - image: youpy/docker-compose-git:latest
    steps:
      - checkout
      # needed to run docker images with docker installed.
      - setup_remote_docker
      - run:
          name: Test project
          command: |
            docker-compose -f local.yml run django mypy connector_street_api

  tests:
    docker:
      - image: youpy/docker-compose-git:latest
    steps:
      - checkout
      # needed to run docker images with docker installed.
      - setup_remote_docker
      - run:
          name: Test project
          command: |
            docker-compose -f local.yml run django pytest



  build-deploy:
    docker:
      - image: vistaprintufi/docker-aws-build
      # - image: hireme/docker-aws-cli:1.0.1
    steps:
      - checkout
      # needed to run docker images with docker installed.
      - setup_remote_docker
      - run:
          name: Test commands
          command: |
            echo $PWD
            ls
            docker --version
            aws --version
            jq --version
      - run:
          name: "Authenticate docker with AWS ECR."
          command: |
            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $ECR_URI
      - run:
          name: "Build, tag and push images"
          command: |
            export IMAGE_TAG="${CIRCLE_WORKFLOW_ID:0:7}"

            # Django
            export REPOSITORY_URI="520099902592.dkr.ecr.us-east-1.amazonaws.com/cstreet_api_production_django"

            sh deployment/build/django.sh

            # Celery Beat
            export REPOSITORY_URI="520099902592.dkr.ecr.us-east-1.amazonaws.com/cstreet_api_production_celerybeat"

            sh deployment/build/django.sh

            # Celery Worker
            export REPOSITORY_URI="520099902592.dkr.ecr.us-east-1.amazonaws.com/cstreet_api_production_celeryworker"

            sh deployment/build/django.sh

            # Flower
            export REPOSITORY_URI="520099902592.dkr.ecr.us-east-1.amazonaws.com/cstreet_api_production_flower"

            sh deployment/build/django.sh

            # Traefik
            export REPOSITORY_URI="520099902592.dkr.ecr.us-east-1.amazonaws.com/cstreet_api_production_traefik"

            sh deployment/build/traefik.sh
      - run:
          name: "Update backend task definition file"
          command: |

            # Create the temporal 'tasks' directory
            mkdir deployment/tasks

            # Retrieve and Save 'backend' task definition in 'tasks' directory
            aws ecs describe-task-definition \
              --task-definition backend \
              --query taskDefinition > deployment/tasks/backend-task-def.json



            # Modify task definition file to new container definition:
            export IMAGE_TAG="${CIRCLE_WORKFLOW_ID:0:7}"

            # Django
            export REPOSITORY_URI="520099902592.dkr.ecr.us-east-1.amazonaws.com/cstreet_api_production_django"

            python3 deployment/scripts/update_task_definition.py \
              --container-name django \
              --image-uri "${REPOSITORY_URI}:${IMAGE_TAG}" \
              --task-definition deployment/tasks/backend-task-def.json

            # Celery Beat
            export REPOSITORY_URI="520099902592.dkr.ecr.us-east-1.amazonaws.com/cstreet_api_production_celerybeat"

            python3 deployment/scripts/update_task_definition.py \
              --container-name celerybeat \
              --image-uri "${REPOSITORY_URI}:${IMAGE_TAG}" \
              --task-definition deployment/tasks/backend-task-def.json

            # Celery Worker
            export REPOSITORY_URI="520099902592.dkr.ecr.us-east-1.amazonaws.com/cstreet_api_production_celeryworker"

            python3 deployment/scripts/update_task_definition.py \
              --container-name celeryworker \
              --image-uri "${REPOSITORY_URI}:${IMAGE_TAG}" \
              --task-definition deployment/tasks/backend-task-def.json

            # Flower
            export REPOSITORY_URI="520099902592.dkr.ecr.us-east-1.amazonaws.com/cstreet_api_production_flower"

            python3 deployment/scripts/update_task_definition.py \
              --container-name flower \
              --image-uri "${REPOSITORY_URI}:${IMAGE_TAG}" \
              --task-definition deployment/tasks/backend-task-def.json

            # Retrieve and Save 'traefik-task-def' task definition in 'tasks' directory
            aws ecs describe-task-definition \
              --task-definition traefik-task-def \
              --query taskDefinition > deployment/tasks/traefik-task-def.json

            # Traefik
            export REPOSITORY_URI="520099902592.dkr.ecr.us-east-1.amazonaws.com/cstreet_api_production_traefik"

            python3 deployment/scripts/update_task_definition.py \
              --container-name traefik \
              --image-uri "${REPOSITORY_URI}:${IMAGE_TAG}" \
              --task-definition deployment/tasks/traefik-task-def.json

            cat deployment/tasks/backend-task-def.json
            cat deployment/tasks/traefik-task-def.json

      - run:
          name: "Update ECS services in AWS"
          command: |

            # Upload new task definition to AWS ECS.
            TASK_DEFINITION_ARN=$(aws ecs register-task-definition \
              --cli-input-json file://deployment/tasks/backend-task-def.json | jq \
              --raw-output '.taskDefinition.taskDefinitionArn')

            CLUSTER_NAME="cstreet-fargate-cluster-prod"

            SERVICE="backend"

            # Update Service with new task definition.
            aws ecs update-service \
              --cluster $CLUSTER_NAME \
              --service $SERVICE \
              --task-definition $TASK_DEFINITION_ARN \
              --force-new-deployment \
              --deployment-configuration "maximumPercent=200,minimumHealthyPercent=100,deploymentCircuitBreaker={enable=true,rollback=true}"

            # Upload new task definition to AWS ECS.
            TASK_DEFINITION_ARN=$(aws ecs register-task-definition \
              --cli-input-json file://deployment/tasks/traefik-task-def.json | jq \
              --raw-output '.taskDefinition.taskDefinitionArn')

            SERVICE="traefik"

            # Update Service with new task definition.
            aws ecs update-service \
              --cluster $CLUSTER_NAME \
              --service $SERVICE \
              --task-definition $TASK_DEFINITION_ARN \
              --force-new-deployment \
              --deployment-configuration "maximumPercent=200,minimumHealthyPercent=100,deploymentCircuitBreaker={enable=true,rollback=true}"
      # - run:
      #     name: "Apply Database migrations."
      #     command: |
      #       CLUSTER_NAME=cstreet-fargate-cluster-prod
      #       TASK=$(aws ecs list-tasks --cluster cstreet-fargate-cluster-prod \
      #         --family backend | jq --raw-output '.taskArns[0]')

      #       aws ecs execute-command --cluster $CLUSTER_NAME \
      #         --task $TASK \
      #         --container django \
      #         --interactive \
      #         --command "python manage.py migrate --no-input"
workflows:
  default:
    jobs:
      - echo-workflow-id
      - static-checks
          requires: [echo-workflow-id]
      - tests
          requires: [static-checks]
      - build-deploy:
          requires: [tests]
          filters:
            branches:
              only: [main]

