# Generated by Django 3.1.12 on 2021-06-22 23:31

import connector_street_api.users.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210622_2324'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', connector_street_api.users.models.CustomUserManager()),
            ],
        ),
    ]
